
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  database: stellar_db_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: stellar_db_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: stellar_db_production
  pool: 5
  timeout: 5000
